### ISSUE TITLE
Error: Could not determine IPFS version on arm64 (Raspberry Pi)

### ISSUE THREAD

**Issue by christroutner** [ipfs/npm-go-ipfs#48]
- node.js version: v16.14.0
- npm version: 8.5.3
- OS: Ubuntu Linux 21.10
- Architecture: arm64 (Raspberry Pi 4)
- npm-go-ipfs current version: 0.13.1

Running this command:
- `npm install go-ipfs`

Results in this error message:

```
npm ERR! code 1
npm ERR! path /home/trout/work/ipfs-p2wdb-service/node_modules/go-ipfs
npm ERR! command failed
npm ERR! command sh -c node src/post-install.js
npm ERR! https://dist.ipfs.io/go-ipfs/versions
npm ERR! Downloading https://dist.ipfs.io/go-ipfs/v0.13.1/go-ipfs_v0.13.1_linux-arm64.tar.gz to /home/trout/.cache/npm-go-ipfs
npm ERR! Downloaded https://dist.ipfs.io/go-ipfs/v0.13.1/go-ipfs_v0.13.1_linux-arm64.tar.gz
npm ERR! Downloading go-ipfs_v0.13.1_linux-arm64.tar.gz.sha512
npm ERR! Downloaded go-ipfs_v0.13.1_linux-arm64.tar.gz.sha512
npm ERR! Verifying go-ipfs_v0.13.1_linux-arm64.tar.gz.sha512
npm ERR! OK (f8e052e57171610d0fa850add62550b7bd4130d1c96f135d2c91dce01a6905d8bc517e1d561a4f89dba981c78e832e2b140bf08cf2ac4a8ecae4857d51ba6177)
npm ERR! Unpacked /home/trout/work/ipfs-p2wdb-service/node_modules/go-ipfs
npm ERR! Linking /home/trout/work/ipfs-p2wdb-service/node_modules/go-ipfs/go-ipfs/ipfs to /home/trout/work/ipfs-p2wdb-service/node_modules/go-ipfs/bin/ipfs
npm ERR! Error: Could not determine IPFS version
npm ERR!     at link (/home/trout/work/ipfs-p2wdb-service/node_modules/go-ipfs/src/download.js:227:11)
npm ERR!     at module.exports (/home/trout/work/ipfs-p2wdb-service/node_modules/go-ipfs/src/download.js:248:10)
npm ERR!     at runMicrotasks (<anonymous>)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trout/.npm/_logs/2022-07-08T05_28_03_475Z-debug-0.log

```

**Comment by lidel** [comment]
I have Raspberry Pi 4 and was unable to reproduce with the latest Ubuntu and  go-ipfs v0.15.0, assuming this got fixed since 0.13.1.
